import os
import time
import sys

os.system("clear")
print("\033[32;1m ")
os.system("figlet Found Dork In Bug Bounty")
print("========================")
print("1)Xss")
print("2)Sql")
print("3)Lfi")
print("4)Info Tools")
print("5)Exit")
print("========================")
select = input("Found It: ")
if select == "1":
	os.system("clear")
	print("wait...")
	time.sleep(5)
	print("========")
	print("Xss Dork:")
	print("inurl://php?feedback­=")
	print("inurl://php?id=")
	print("inurl://search.php?q=")
	print("inurl://php?txt=")
	print("inurl://news.php?id=")
	print("inurl://shop.php?id=")
	print("========")
	print("Go To Xss!")
elif select == "2":
	os.system("clear")
	print("========")
	print("Sql Dork:")
	print("php?id=")
	print("ShowProduct.asp?CatID=")
	print("news.php?id=")
	print("shopdisplayproducts.cfm?id=")
	print("product.php?id=")
	print("category.asp?catid=")
	print("========")
	print("Go To Sql!")
elif select == "3":
	os.system("clear")
	print("========")
	print("Lfi Dork:")
	print("/index.php?from_market=Y&pageurl=")
	print("index.php?pagina=empresa.php")
	print("inurl://php?page=")
	print("/index.php?open=")
	print("index.php?content=")
	print("=========")
	print("Go To Lfi!")
elif select == "4":
	print("This tool is for finding dorks that are vulnerable to bug bounties so that pentesters can work easily")
elif select == "5":
	print("=======")
	print("Good Bye")
	print("=======")
	sys.exit(3)
